### ISSUE TITLE
Conversion error in Xcode 14.3+ and macOS 13

### ISSUE THREAD

**Issue by cbaker6** [sersoft-gmbh/swift-coverage-action#146]
Running into an issue whenever I attempt to use this action on macOS 13, my errors seem related to `xcrun` and can be found here: https://github.com/netreconlab/Parse-Swift/actions/runs/5366235085/jobs/9735553247?pr=87#step:6:22

**Comment by ffried** [comment]
Hmm, I cannot reproduce it by using macOS 13. See [this run](https://github.com/sersoft-gmbh/semver/actions/runs/5369704829/jobs/9741336636) in one of our open source projects.

It's using Xcode 14.3.1 and macOS 13.4.

Also, the warnings emitted before the failure hint at some "invalid" files (invalid from `llvm-cov`'s point of view).
I've noticed, that they either reside inside a folder called `EagerLinkingTBDs` or `VerifyModule`. I wonder if those are new somehow...
I've added a check for the products directory when processing xcode builds on `main`(https://github.com/sersoft-gmbh/swift-coverage-action/commit/27b9eb2d7bfa7aecc5ad863642d1207d3b6bf1b4). Can you test your setup with `@main`? If it works, I'll release a new version.

**Comment by cbaker6** [comment]
> I've added a check for the products directory when processing xcode builds on main(https://github.com/sersoft-gmbh/swift-coverage-action/commit/27b9eb2d7bfa7aecc5ad863642d1207d3b6bf1b4). Can you test your setup with @main? If it works, I'll release a new version.

Tested using `@main` as you recommended and it works! Here's my latest build https://github.com/netreconlab/Parse-Swift/actions/runs/5370710459?pr=87

**Comment by ffried** [comment]
I've released v3.0.2 containing this fix. So you should be able to go back to `@v3`.

**Comment by cbaker6** [comment]
@ffried thanks for fixing this so quickly!
