### ISSUE TITLE
Difference in results when using lcov and txt

### ISSUE THREAD

**Issue by cbaker6** [sersoft-gmbh/swift-coverage-action#37]
I'm seeing a significant difference in the codecov results when using `lcov` (better) vs `txt`. For example, I've been testing out each in a [PR](https://github.com/parse-community/Parse-Swift/pull/277):

Using lcov:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/8621344/140795812-4c6070f0-2259-42ec-a842-3f9efa2af63f.png">

Using txt:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/8621344/140796069-fc24386b-8346-41ee-bc9e-d2929228ad47.png">

Notice that lcov `10574` lines and txt is only finding `10092`. In addition the percentage covered is significantly different.

For comparison, my Xcode produced codecov is below which is significantly higher than both:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/8621344/140796324-8faefb86-6d4b-4953-9809-8681eba8c1de.png">

I know that there's going to be a difference in between what Xcode and gcov produces. My two questions are:

1. Do you think there may be a parsing issue?
2. If the difference can't be overcome do you think the default should be `lcov`?

My actions file that produces lcov is [here](https://github.com/parse-community/Parse-Swift/blob/d3ea1bd50030a7035180a6d668beba97876254d9/.github/workflows/ci.yml) and txt [here](https://github.com/parse-community/Parse-Swift/blob/legacyCodecov/.github/workflows/ci.yml).

**Comment by ffried** [comment]
First of all, this action doesn't really parse any coverage files. It simply executes a series of commands producing a bunch of files. Parsing is then done by the tool that consumes them (in your case codecov).

Generally, I'd advice to use `format: lcov`, though. The reason it's not the default is that this would be a breaking change. And releasing a new major version just with this changes seems a bit overkill :)

**Comment by ffried** [comment]
I've released version 3.0.0 which changes the default format to lcov.
